/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Area: typeof import('./src/components/Base/Area.vue')['default']
    AreaChart: typeof import('./src/components/Pages/AreaChart.vue')['default']
    AreaChartPage: typeof import('./src/components/Pages/AreaChartPage.vue')['default']
    AreaStacked: typeof import('./src/components/Base/AreaStacked.vue')['default']
    Bar: typeof import('./src/components/Base/Bar.vue')['default']
    BarChart: typeof import('./src/components/BarChart.vue')['default']
    BarChartPage: typeof import('./src/components/Pages/BarChartPage.vue')['default']
    Button: typeof import('./src/components/Elements/Button.vue')['default']
    Card: typeof import('./src/components/Elements/Card.vue')['default']
    copy: typeof import('./src/components/Pages/LineChartPage copy.vue')['default']
    Crosshair: typeof import('./src/components/Base/Crosshair.vue')['default']
    Donut: typeof import('./src/components/Base/Donut.vue')['default']
    DonutChart: typeof import('./src/components/DonutChart.vue')['default']
    DonutChartPage: typeof import('./src/components/Pages/DonutChartPage.vue')['default']
    Homepage: typeof import('./src/components/Homepage.vue')['default']
    Index: typeof import('./src/components/Base/Line/Index.vue')['default']
    Line: typeof import('./src/components/Base/Line/Line.vue')['default']
    LineChartPage: typeof import('./src/components/Pages/LineChartPage.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Overview: typeof import('./src/components/Overview.vue')['default']
    Progress: typeof import('./src/components/Base/Progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Status: typeof import('./src/components/Base/Status.vue')['default']
    Table: typeof import('./src/components/Elements/Table/Table.vue')['default']
    TablePage: typeof import('./src/components/Pages/TablePage.vue')['default']
    Test3d: typeof import('./src/components/Test3d.vue')['default']
    Tooltip: typeof import('./src/components/Base/Tooltip.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.12_@babel+parser@7.26.8_embla-carousel@8.5.2_radix-vue@1.9.13_vue@3.5.13_x422h3vsgrgcvkoya6nlnhdf5i/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.12_@babel+parser@7.26.8_embla-carousel@8.5.2_radix-vue@1.9.13_vue@3.5.13_x422h3vsgrgcvkoya6nlnhdf5i/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.12_@babel+parser@7.26.8_embla-carousel@8.5.2_radix-vue@1.9.13_vue@3.5.13_x422h3vsgrgcvkoya6nlnhdf5i/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.12_@babel+parser@7.26.8_embla-carousel@8.5.2_radix-vue@1.9.13_vue@3.5.13_x422h3vsgrgcvkoya6nlnhdf5i/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.12_@babel+parser@7.26.8_embla-carousel@8.5.2_radix-vue@1.9.13_vue@3.5.13_x422h3vsgrgcvkoya6nlnhdf5i/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    ULinkBase: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.12_@babel+parser@7.26.8_embla-carousel@8.5.2_radix-vue@1.9.13_vue@3.5.13_x422h3vsgrgcvkoya6nlnhdf5i/node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
    UTable: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.12_@babel+parser@7.26.8_embla-carousel@8.5.2_radix-vue@1.9.13_vue@3.5.13_x422h3vsgrgcvkoya6nlnhdf5i/node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
  }
}
